# Generated by Django 4.1.7 on 2023-03-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ptac',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ptc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ptra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='puissance',
            field=models.CharField(blank=True, choices=[('die', 'Diesel'), ('ess', 'Essance'), ('ele', 'Electrique')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('TH', 'Travaux en hauteur'), ('TE', 'Terrassement & Extraction'), ('LM', 'Levage & Manutention'), ('CT', 'Chargement & Transport'), ('GD', 'Gros Oeuvre & Démolition')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_debut',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_fin',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('CNP', 'Camion Nacelle PT'), ('CNV', 'Camion Nacelle VI'), ('ER', 'Echaffaudage Roulant'), ('NA', 'Nacelle Araignée'), ('NAR', 'Nacelle Articulée'), ('NC', 'Nacelle Ciseaux'), ('NT', 'Nacelle Telescopique'), ('NTC', 'Nacelle Toucon'), ('NEL', 'Nacelle Elevatrice'), ('B', 'Buldozer'), ('C', 'Chargeuse'), ('MC', 'Mini Chargeuse'), ('MP', 'Mini Pelle'), ('P', 'Pelleteuse'), ('CH', 'Chariot Elevateur'), ('CT', 'Chariot Telescopique'), ('GT', 'Gerbeur & Transpalette'), ('GMV', 'Glaslift: Monte vitre'), ('G', 'Grue Mobile'), ('GSR', 'Grue sur remorque'), ('MGA', 'Mini Grue araignée'), ('MGB', 'Mini Grue mobile'), ('MCA', 'Monte Charge'), ('BE', 'Benne'), ('CB', 'Camion Benne'), ('CBG', 'Camion Bras de grue'), ('TOM', 'Tombereau'), ('RB', 'Rebot de démolition')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='prix_avec_livraison_reprise',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='prix_avec_operateur',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
