# Generated by Django 4.1.7 on 2023-03-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_item_ptac_item_ptc_item_ptra_item_puissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='commentaire',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='is_approuved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='annonce_responde',
            name='commentaire',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='mode_location',
            field=models.CharField(blank=True, choices=[('PJ', 'Jour'), ('PH', 'Heure')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='puissance',
            field=models.CharField(blank=True, choices=[('die', 'Diesel'), ('ele', 'Electrique'), ('ess', 'Essence')], max_length=3, null=True),
        ),
    ]
