# Generated by Django 4.1.7 on 2023-03-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_annonce_commentaire_annonce_is_approuved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='is_rejected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
