# Generated by Django 4.1.7 on 2023-03-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_annonce_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reference',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='mode_location',
            field=models.CharField(blank=True, choices=[('PH', 'Heure'), ('PJ', 'Jour')], max_length=2, null=True),
        ),
    ]
