# Generated by Django 4.1.7 on 2023-03-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_item_reference_alter_item_mode_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='commentaire',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_approuved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='mode_location',
            field=models.CharField(blank=True, choices=[('PJ', 'Jour'), ('PH', 'Heure')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='puissance',
            field=models.CharField(blank=True, choices=[('die', 'Diesel'), ('ess', 'Essence'), ('ele', 'Electrique')], max_length=3, null=True),
        ),
    ]
