# Generated by Django 4.1.7 on 2023-03-20 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_item_commentaire_item_is_approuved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='puissance',
            field=models.CharField(blank=True, choices=[('ess', 'Essence'), ('ele', 'Electrique'), ('die', 'Diesel')], max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='SignaledItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motifs', models.CharField(blank=True, max_length=1000, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Signalement de l'article",
                'verbose_name_plural': 'Signalements des articles',
            },
        ),
    ]
