# Generated by Django 4.1.7 on 2023-03-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_item_puissance_signaleditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mode_location',
            field=models.CharField(blank=True, choices=[('PH', 'Heure'), ('PJ', 'Jour')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='puissance',
            field=models.CharField(blank=True, choices=[('ess', 'Essence'), ('die', 'Diesel'), ('ele', 'Electrique')], max_length=3, null=True),
        ),
    ]
